name: drobe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  palette_generator: ^0.3.3
  image: ^4.5.4
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  flutter_colorpicker: ^1.0.3
  geolocator: ^13.0.2
  share_plus: ^7.0.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  file_picker: ^5.3.2
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.2
  provider: ^6.1.4

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/drobe_logo.png
    - assets/images/drobe_icon.png

  # Move fonts section inside flutter section
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 300
        - asset: assets/fonts/AvenirLTStd-Roman.otf
          weight: 400
        - asset: assets/fonts/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-Heavy.otf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/drobe_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/drobe_icon.png"

